# ***** BEGIN GPL LICENSE BLOCK *****
#
# --------------------------------------------------------------------------
# Blender 2.5 LuxRender Add-On
# --------------------------------------------------------------------------
#
# This preset file was generated by LuxBlend25 and modified by Jason Clarke
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.
#
# ***** END GPL LICENCE BLOCK *****
#

import bpy
bpy.context.scene.luxrender_rendermode.rendermode = 'bidirectional'
bpy.context.scene.luxrender_engine.fixed_seed = False
bpy.context.scene.luxrender_sampler.sampler = 'metropolis'
bpy.context.scene.luxrender_sampler.largemutationprob = 0.4000000059604645
bpy.context.scene.luxrender_sampler.maxconsecrejects = 512
bpy.context.scene.luxrender_sampler.usecooldown = False
bpy.context.scene.luxrender_sampler.usevariance = False
bpy.context.scene.luxrender_integrator.lightpathstrategy = 'auto'
bpy.context.scene.luxrender_integrator.lightstrategy = 'auto'
bpy.context.scene.luxrender_integrator.eyedepth = 48
bpy.context.scene.luxrender_integrator.lightdepth = 48
bpy.context.scene.luxrender_integrator.eyerrthreshold = 0.0
bpy.context.scene.luxrender_integrator.lightrrthreshold = 0.0
bpy.context.scene.luxrender_volumeintegrator.volumeintegrator = 'multi'
bpy.context.scene.luxrender_volumeintegrator.stepsize = 1.0