# ***** BEGIN GPL LICENSE BLOCK *****
#
# --------------------------------------------------------------------------
# Blender 2.5 LuxRender Add-On
# --------------------------------------------------------------------------
#
# This preset file was generated by LuxBlend25 and modified by Jason Clarke
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.
#
# ***** END GPL LICENCE BLOCK *****
#

import bpy
bpy.context.scene.luxrender_rendermode.rendermode = 'directlighting'
bpy.context.scene.luxrender_rendermode.renderer = 'sampler'
bpy.context.scene.luxrender_sampler.sampler = 'random'
bpy.context.scene.luxrender_sampler.pixelsampler = 'vegas'
bpy.context.scene.luxrender_sampler.pixelsamples = 1
bpy.context.scene.luxrender_integrator.surfaceintegrator = 'directlighting'
bpy.context.scene.luxrender_integrator.lightstrategy = 'auto'
bpy.context.scene.luxrender_integrator.maxdepth = 16
bpy.context.scene.luxrender_integrator.rrstrategy = 'efficiency'
bpy.context.scene.luxrender_integrator.includeenvironment = True
bpy.context.scene.luxrender_volumeintegrator.volumeintegrator = 'single'
bpy.context.scene.luxrender_volumeintegrator.stepsize = 1.0
bpy.context.scene.luxrender_accelerator.accelerator = 'bvh'
bpy.context.scene.luxrender_accelerator.advanced = False
bpy.context.scene.luxrender_accelerator.intersectcost = 80
bpy.context.scene.luxrender_accelerator.traversalcost = 1
bpy.context.scene.luxrender_accelerator.emptybonus = 0.20000000298023224
bpy.context.scene.luxrender_accelerator.treetype = '2'
bpy.context.scene.luxrender_accelerator.costsample = 0
bpy.context.scene.luxrender_accelerator.maxprims = 1
bpy.context.scene.luxrender_accelerator.maxdepth = -1
bpy.context.scene.luxrender_accelerator.refineimmediately = False
bpy.context.scene.luxrender_accelerator.maxprimsperleaf = 4
bpy.context.scene.luxrender_accelerator.fullsweepthreshold = 16
bpy.context.scene.luxrender_accelerator.skipfactor = 1
